server:
  port: 8088

---

spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
  cloud:
    gateway:
      routes:
         - id: customer
           uri: http://localhost:8082
           predicates:
            - Path= 
         - id: store
           uri: http://localhost:8083
           predicates:
            - Path= 
         - id: rider
           uri: http://localhost:8084
           predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://oauth:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path= 
        - id: store
          uri: http://store:8080
          predicates:
            - Path= 
        - id: rider
          uri: http://rider:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080